// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: raw.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	pb "m7s.live/v5/pb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 帧类型枚举
type FrameType int32

const (
	FrameType_UNKNOWN FrameType = 0
	FrameType_AUDIO   FrameType = 1
	FrameType_VIDEO   FrameType = 2
)

// Enum value maps for FrameType.
var (
	FrameType_name = map[int32]string{
		0: "UNKNOWN",
		1: "AUDIO",
		2: "VIDEO",
	}
	FrameType_value = map[string]int32{
		"UNKNOWN": 0,
		"AUDIO":   1,
		"VIDEO":   2,
	}
)

func (x FrameType) Enum() *FrameType {
	p := new(FrameType)
	*p = x
	return p
}

func (x FrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_raw_proto_enumTypes[0].Descriptor()
}

func (FrameType) Type() protoreflect.EnumType {
	return &file_raw_proto_enumTypes[0]
}

func (x FrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameType.Descriptor instead.
func (FrameType) EnumDescriptor() ([]byte, []int) {
	return file_raw_proto_rawDescGZIP(), []int{0}
}

// 订阅请求
type SubscribeRawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamPath    string                 `protobuf:"bytes,1,opt,name=streamPath,proto3" json:"streamPath,omitempty"`                          // 流路径，例如: "live/stream1"
	IncludeAudio  bool                   `protobuf:"varint,2,opt,name=include_audio,json=includeAudio,proto3" json:"include_audio,omitempty"` // 是否包含音频数据
	IncludeVideo  bool                   `protobuf:"varint,3,opt,name=include_video,json=includeVideo,proto3" json:"include_video,omitempty"` // 是否包含视频数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRawRequest) Reset() {
	*x = SubscribeRawRequest{}
	mi := &file_raw_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRawRequest) ProtoMessage() {}

func (x *SubscribeRawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raw_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRawRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRawRequest) Descriptor() ([]byte, []int) {
	return file_raw_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRawRequest) GetStreamPath() string {
	if x != nil {
		return x.StreamPath
	}
	return ""
}

func (x *SubscribeRawRequest) GetIncludeAudio() bool {
	if x != nil {
		return x.IncludeAudio
	}
	return false
}

func (x *SubscribeRawRequest) GetIncludeVideo() bool {
	if x != nil {
		return x.IncludeVideo
	}
	return false
}

type StreamInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamPath    string                 `protobuf:"bytes,1,opt,name=streamPath,proto3" json:"streamPath,omitempty"` // 流路径，例如: "live/stream1"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInfoRequest) Reset() {
	*x = StreamInfoRequest{}
	mi := &file_raw_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInfoRequest) ProtoMessage() {}

func (x *StreamInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raw_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInfoRequest.ProtoReflect.Descriptor instead.
func (*StreamInfoRequest) Descriptor() ([]byte, []int) {
	return file_raw_proto_rawDescGZIP(), []int{1}
}

func (x *StreamInfoRequest) GetStreamPath() string {
	if x != nil {
		return x.StreamPath
	}
	return ""
}

type RawFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamPath    string                 `protobuf:"bytes,1,opt,name=streamPath,proto3" json:"streamPath,omitempty"`                                    // 流路径
	FrameType     FrameType              `protobuf:"varint,2,opt,name=frame_type,json=frameType,proto3,enum=raw.FrameType" json:"frame_type,omitempty"` // 帧类型 (音频/视频)
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                     // 时间戳
	NalData       []byte                 `protobuf:"bytes,4,opt,name=nal_data,json=nalData,proto3" json:"nal_data,omitempty"`                           // NAL单元数据
	IsKeyframe    bool                   `protobuf:"varint,6,opt,name=is_keyframe,json=isKeyframe,proto3" json:"is_keyframe,omitempty"`                 // 是否是关键帧
	CodecInfo     *CodecInfo             `protobuf:"bytes,7,opt,name=codec_info,json=codecInfo,proto3" json:"codec_info,omitempty"`                     // 编解码器信息
	Size          int64                  `protobuf:"varint,9,opt,name=size,proto3" json:"size,omitempty"`                                               // 数据大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawFrame) Reset() {
	*x = RawFrame{}
	mi := &file_raw_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawFrame) ProtoMessage() {}

func (x *RawFrame) ProtoReflect() protoreflect.Message {
	mi := &file_raw_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawFrame.ProtoReflect.Descriptor instead.
func (*RawFrame) Descriptor() ([]byte, []int) {
	return file_raw_proto_rawDescGZIP(), []int{2}
}

func (x *RawFrame) GetStreamPath() string {
	if x != nil {
		return x.StreamPath
	}
	return ""
}

func (x *RawFrame) GetFrameType() FrameType {
	if x != nil {
		return x.FrameType
	}
	return FrameType_UNKNOWN
}

func (x *RawFrame) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RawFrame) GetNalData() []byte {
	if x != nil {
		return x.NalData
	}
	return nil
}

func (x *RawFrame) GetIsKeyframe() bool {
	if x != nil {
		return x.IsKeyframe
	}
	return false
}

func (x *RawFrame) GetCodecInfo() *CodecInfo {
	if x != nil {
		return x.CodecInfo
	}
	return nil
}

func (x *RawFrame) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SubscribeListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StreamPath    []string               `protobuf:"bytes,3,rep,name=streamPath,proto3" json:"streamPath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeListResponse) Reset() {
	*x = SubscribeListResponse{}
	mi := &file_raw_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeListResponse) ProtoMessage() {}

func (x *SubscribeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raw_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeListResponse.ProtoReflect.Descriptor instead.
func (*SubscribeListResponse) Descriptor() ([]byte, []int) {
	return file_raw_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeListResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SubscribeListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubscribeListResponse) GetStreamPath() []string {
	if x != nil {
		return x.StreamPath
	}
	return nil
}

// 编解码器信息
type CodecInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CodecName     string                 `protobuf:"bytes,1,opt,name=codec_name,json=codecName,proto3" json:"codec_name,omitempty"` // 编解码器名称 (H264, H265, AAC等)
	Width         int64                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`                         // 视频宽度 (仅视频)
	Height        int64                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`                       // 视频高度 (仅视频)
	Fps           int64                  `protobuf:"varint,4,opt,name=fps,proto3" json:"fps,omitempty"`
	SampleRate    int64                  `protobuf:"varint,5,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"` // 音频采样率 (仅音频)
	Channels      int64                  `protobuf:"varint,6,opt,name=channels,proto3" json:"channels,omitempty"`                       // 音频通道数 (仅音频)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodecInfo) Reset() {
	*x = CodecInfo{}
	mi := &file_raw_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodecInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodecInfo) ProtoMessage() {}

func (x *CodecInfo) ProtoReflect() protoreflect.Message {
	mi := &file_raw_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodecInfo.ProtoReflect.Descriptor instead.
func (*CodecInfo) Descriptor() ([]byte, []int) {
	return file_raw_proto_rawDescGZIP(), []int{4}
}

func (x *CodecInfo) GetCodecName() string {
	if x != nil {
		return x.CodecName
	}
	return ""
}

func (x *CodecInfo) GetWidth() int64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CodecInfo) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CodecInfo) GetFps() int64 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *CodecInfo) GetSampleRate() int64 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *CodecInfo) GetChannels() int64 {
	if x != nil {
		return x.Channels
	}
	return 0
}

// 流列表响应
type StreamListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Streams       []*StreamInfo          `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"` // 可用的流列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamListResponse) Reset() {
	*x = StreamListResponse{}
	mi := &file_raw_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamListResponse) ProtoMessage() {}

func (x *StreamListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raw_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamListResponse.ProtoReflect.Descriptor instead.
func (*StreamListResponse) Descriptor() ([]byte, []int) {
	return file_raw_proto_rawDescGZIP(), []int{5}
}

func (x *StreamListResponse) GetStreams() []*StreamInfo {
	if x != nil {
		return x.Streams
	}
	return nil
}

// 流信息
type StreamInfo struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StreamPath string                 `protobuf:"bytes,1,opt,name=stream_path,json=streamPath,proto3" json:"stream_path,omitempty"` // 流路径
	StreamType string                 `protobuf:"bytes,2,opt,name=stream_type,json=streamType,proto3" json:"stream_type,omitempty"` // 流类型
	// google.protobuf.Timestamp created_time = 3;  // 创建时间
	HasAudio      bool       `protobuf:"varint,4,opt,name=has_audio,json=hasAudio,proto3" json:"has_audio,omitempty"`      // 是否有音频
	HasVideo      bool       `protobuf:"varint,5,opt,name=has_video,json=hasVideo,proto3" json:"has_video,omitempty"`      // 是否有视频
	AudioCodec    *CodecInfo `protobuf:"bytes,6,opt,name=audio_codec,json=audioCodec,proto3" json:"audio_codec,omitempty"` // 音频编解码器信息
	VideoCodec    *CodecInfo `protobuf:"bytes,7,opt,name=video_codec,json=videoCodec,proto3" json:"video_codec,omitempty"` // 视频编解码器信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInfo) Reset() {
	*x = StreamInfo{}
	mi := &file_raw_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInfo) ProtoMessage() {}

func (x *StreamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_raw_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInfo.ProtoReflect.Descriptor instead.
func (*StreamInfo) Descriptor() ([]byte, []int) {
	return file_raw_proto_rawDescGZIP(), []int{6}
}

func (x *StreamInfo) GetStreamPath() string {
	if x != nil {
		return x.StreamPath
	}
	return ""
}

func (x *StreamInfo) GetStreamType() string {
	if x != nil {
		return x.StreamType
	}
	return ""
}

func (x *StreamInfo) GetHasAudio() bool {
	if x != nil {
		return x.HasAudio
	}
	return false
}

func (x *StreamInfo) GetHasVideo() bool {
	if x != nil {
		return x.HasVideo
	}
	return false
}

func (x *StreamInfo) GetAudioCodec() *CodecInfo {
	if x != nil {
		return x.AudioCodec
	}
	return nil
}

func (x *StreamInfo) GetVideoCodec() *CodecInfo {
	if x != nil {
		return x.VideoCodec
	}
	return nil
}

var File_raw_proto protoreflect.FileDescriptor

const file_raw_proto_rawDesc = "" +
	"\n" +
	"\traw.proto\x12\x03raw\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\fglobal.proto\"\x7f\n" +
	"\x13SubscribeRawRequest\x12\x1e\n" +
	"\n" +
	"streamPath\x18\x01 \x01(\tR\n" +
	"streamPath\x12#\n" +
	"\rinclude_audio\x18\x02 \x01(\bR\fincludeAudio\x12#\n" +
	"\rinclude_video\x18\x03 \x01(\bR\fincludeVideo\"3\n" +
	"\x11StreamInfoRequest\x12\x1e\n" +
	"\n" +
	"streamPath\x18\x01 \x01(\tR\n" +
	"streamPath\"\xf6\x01\n" +
	"\bRawFrame\x12\x1e\n" +
	"\n" +
	"streamPath\x18\x01 \x01(\tR\n" +
	"streamPath\x12-\n" +
	"\n" +
	"frame_type\x18\x02 \x01(\x0e2\x0e.raw.FrameTypeR\tframeType\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x19\n" +
	"\bnal_data\x18\x04 \x01(\fR\analData\x12\x1f\n" +
	"\vis_keyframe\x18\x06 \x01(\bR\n" +
	"isKeyframe\x12-\n" +
	"\n" +
	"codec_info\x18\a \x01(\v2\x0e.raw.CodecInfoR\tcodecInfo\x12\x12\n" +
	"\x04size\x18\t \x01(\x03R\x04size\"e\n" +
	"\x15SubscribeListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"streamPath\x18\x03 \x03(\tR\n" +
	"streamPath\"\xa7\x01\n" +
	"\tCodecInfo\x12\x1d\n" +
	"\n" +
	"codec_name\x18\x01 \x01(\tR\tcodecName\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x03R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x03R\x06height\x12\x10\n" +
	"\x03fps\x18\x04 \x01(\x03R\x03fps\x12\x1f\n" +
	"\vsample_rate\x18\x05 \x01(\x03R\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\x06 \x01(\x03R\bchannels\"?\n" +
	"\x12StreamListResponse\x12)\n" +
	"\astreams\x18\x01 \x03(\v2\x0f.raw.StreamInfoR\astreams\"\xea\x01\n" +
	"\n" +
	"StreamInfo\x12\x1f\n" +
	"\vstream_path\x18\x01 \x01(\tR\n" +
	"streamPath\x12\x1f\n" +
	"\vstream_type\x18\x02 \x01(\tR\n" +
	"streamType\x12\x1b\n" +
	"\thas_audio\x18\x04 \x01(\bR\bhasAudio\x12\x1b\n" +
	"\thas_video\x18\x05 \x01(\bR\bhasVideo\x12/\n" +
	"\vaudio_codec\x18\x06 \x01(\v2\x0e.raw.CodecInfoR\n" +
	"audioCodec\x12/\n" +
	"\vvideo_codec\x18\a \x01(\v2\x0e.raw.CodecInfoR\n" +
	"videoCodec*.\n" +
	"\tFrameType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05AUDIO\x10\x01\x12\t\n" +
	"\x05VIDEO\x10\x022\x83\x03\n" +
	"\x03api\x12;\n" +
	"\fSubscribeRaw\x12\x18.raw.SubscribeRawRequest\x1a\r.raw.RawFrame\"\x000\x01\x12q\n" +
	"\x0eUnsubscribeRaw\x12\x18.raw.SubscribeRawRequest\x1a\x17.global.SuccessResponse\",\x82\xd3\xe4\x93\x02&\"$/raw/api/unsubscribe/{streamPath=**}\x12b\n" +
	"\x11UnsubscribeAllRaw\x12\x16.google.protobuf.Empty\x1a\x17.global.SuccessResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\"\x14/raw/api/unsubscribe\x12h\n" +
	"\x13GetSubscribeRawList\x12\x16.google.protobuf.Empty\x1a\x1a.raw.SubscribeListResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/raw/api/getsubscribeB\x1bZ\x19m7s.live/v5/plugin/raw/pbb\x06proto3"

var (
	file_raw_proto_rawDescOnce sync.Once
	file_raw_proto_rawDescData []byte
)

func file_raw_proto_rawDescGZIP() []byte {
	file_raw_proto_rawDescOnce.Do(func() {
		file_raw_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raw_proto_rawDesc), len(file_raw_proto_rawDesc)))
	})
	return file_raw_proto_rawDescData
}

var file_raw_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_raw_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_raw_proto_goTypes = []any{
	(FrameType)(0),                // 0: raw.FrameType
	(*SubscribeRawRequest)(nil),   // 1: raw.SubscribeRawRequest
	(*StreamInfoRequest)(nil),     // 2: raw.StreamInfoRequest
	(*RawFrame)(nil),              // 3: raw.RawFrame
	(*SubscribeListResponse)(nil), // 4: raw.SubscribeListResponse
	(*CodecInfo)(nil),             // 5: raw.CodecInfo
	(*StreamListResponse)(nil),    // 6: raw.StreamListResponse
	(*StreamInfo)(nil),            // 7: raw.StreamInfo
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
	(*pb.SuccessResponse)(nil),    // 9: global.SuccessResponse
}
var file_raw_proto_depIdxs = []int32{
	0, // 0: raw.RawFrame.frame_type:type_name -> raw.FrameType
	5, // 1: raw.RawFrame.codec_info:type_name -> raw.CodecInfo
	7, // 2: raw.StreamListResponse.streams:type_name -> raw.StreamInfo
	5, // 3: raw.StreamInfo.audio_codec:type_name -> raw.CodecInfo
	5, // 4: raw.StreamInfo.video_codec:type_name -> raw.CodecInfo
	1, // 5: raw.api.SubscribeRaw:input_type -> raw.SubscribeRawRequest
	1, // 6: raw.api.UnsubscribeRaw:input_type -> raw.SubscribeRawRequest
	8, // 7: raw.api.UnsubscribeAllRaw:input_type -> google.protobuf.Empty
	8, // 8: raw.api.GetSubscribeRawList:input_type -> google.protobuf.Empty
	3, // 9: raw.api.SubscribeRaw:output_type -> raw.RawFrame
	9, // 10: raw.api.UnsubscribeRaw:output_type -> global.SuccessResponse
	9, // 11: raw.api.UnsubscribeAllRaw:output_type -> global.SuccessResponse
	4, // 12: raw.api.GetSubscribeRawList:output_type -> raw.SubscribeListResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_raw_proto_init() }
func file_raw_proto_init() {
	if File_raw_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raw_proto_rawDesc), len(file_raw_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_raw_proto_goTypes,
		DependencyIndexes: file_raw_proto_depIdxs,
		EnumInfos:         file_raw_proto_enumTypes,
		MessageInfos:      file_raw_proto_msgTypes,
	}.Build()
	File_raw_proto = out.File
	file_raw_proto_goTypes = nil
	file_raw_proto_depIdxs = nil
}
