// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.31.1
// source: raw.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	pb "m7s.live/v5/pb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Api_SubscribeRaw_FullMethodName        = "/raw.api/SubscribeRaw"
	Api_UnsubscribeRaw_FullMethodName      = "/raw.api/UnsubscribeRaw"
	Api_UnsubscribeAllRaw_FullMethodName   = "/raw.api/UnsubscribeAllRaw"
	Api_GetSubscribeRawList_FullMethodName = "/raw.api/GetSubscribeRawList"
)

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiClient interface {
	SubscribeRaw(ctx context.Context, in *SubscribeRawRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RawFrame], error)
	// 取消订阅
	UnsubscribeRaw(ctx context.Context, in *SubscribeRawRequest, opts ...grpc.CallOption) (*pb.SuccessResponse, error)
	// 取消所有订阅
	UnsubscribeAllRaw(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*pb.SuccessResponse, error)
	GetSubscribeRawList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SubscribeListResponse, error)
}

type apiClient struct {
	cc grpc.ClientConnInterface
}

func NewApiClient(cc grpc.ClientConnInterface) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) SubscribeRaw(ctx context.Context, in *SubscribeRawRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RawFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[0], Api_SubscribeRaw_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRawRequest, RawFrame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_SubscribeRawClient = grpc.ServerStreamingClient[RawFrame]

func (c *apiClient) UnsubscribeRaw(ctx context.Context, in *SubscribeRawRequest, opts ...grpc.CallOption) (*pb.SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.SuccessResponse)
	err := c.cc.Invoke(ctx, Api_UnsubscribeRaw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) UnsubscribeAllRaw(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*pb.SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.SuccessResponse)
	err := c.cc.Invoke(ctx, Api_UnsubscribeAllRaw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetSubscribeRawList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SubscribeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscribeListResponse)
	err := c.cc.Invoke(ctx, Api_GetSubscribeRawList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
// All implementations must embed UnimplementedApiServer
// for forward compatibility.
type ApiServer interface {
	SubscribeRaw(*SubscribeRawRequest, grpc.ServerStreamingServer[RawFrame]) error
	// 取消订阅
	UnsubscribeRaw(context.Context, *SubscribeRawRequest) (*pb.SuccessResponse, error)
	// 取消所有订阅
	UnsubscribeAllRaw(context.Context, *emptypb.Empty) (*pb.SuccessResponse, error)
	GetSubscribeRawList(context.Context, *emptypb.Empty) (*SubscribeListResponse, error)
	mustEmbedUnimplementedApiServer()
}

// UnimplementedApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApiServer struct{}

func (UnimplementedApiServer) SubscribeRaw(*SubscribeRawRequest, grpc.ServerStreamingServer[RawFrame]) error {
	return status.Error(codes.Unimplemented, "method SubscribeRaw not implemented")
}
func (UnimplementedApiServer) UnsubscribeRaw(context.Context, *SubscribeRawRequest) (*pb.SuccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnsubscribeRaw not implemented")
}
func (UnimplementedApiServer) UnsubscribeAllRaw(context.Context, *emptypb.Empty) (*pb.SuccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnsubscribeAllRaw not implemented")
}
func (UnimplementedApiServer) GetSubscribeRawList(context.Context, *emptypb.Empty) (*SubscribeListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubscribeRawList not implemented")
}
func (UnimplementedApiServer) mustEmbedUnimplementedApiServer() {}
func (UnimplementedApiServer) testEmbeddedByValue()             {}

// UnsafeApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiServer will
// result in compilation errors.
type UnsafeApiServer interface {
	mustEmbedUnimplementedApiServer()
}

func RegisterApiServer(s grpc.ServiceRegistrar, srv ApiServer) {
	// If the following call panics, it indicates UnimplementedApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Api_ServiceDesc, srv)
}

func _Api_SubscribeRaw_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRawRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).SubscribeRaw(m, &grpc.GenericServerStream[SubscribeRawRequest, RawFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_SubscribeRawServer = grpc.ServerStreamingServer[RawFrame]

func _Api_UnsubscribeRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).UnsubscribeRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_UnsubscribeRaw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).UnsubscribeRaw(ctx, req.(*SubscribeRawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_UnsubscribeAllRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).UnsubscribeAllRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_UnsubscribeAllRaw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).UnsubscribeAllRaw(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetSubscribeRawList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetSubscribeRawList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_GetSubscribeRawList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetSubscribeRawList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Api_ServiceDesc is the grpc.ServiceDesc for Api service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Api_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "raw.api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnsubscribeRaw",
			Handler:    _Api_UnsubscribeRaw_Handler,
		},
		{
			MethodName: "UnsubscribeAllRaw",
			Handler:    _Api_UnsubscribeAllRaw_Handler,
		},
		{
			MethodName: "GetSubscribeRawList",
			Handler:    _Api_GetSubscribeRawList_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeRaw",
			Handler:       _Api_SubscribeRaw_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "raw.proto",
}
